name: task_cubit
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc:
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/colors.json

